### ISSUE TITLE
Report is blank for VB365 possibly due to some organizations still on basic authentication

### ISSUE THREAD

**Issue by HangTen416** [VeeamHub/veeam-healthcheck#19]
**Describe the bug**
When this script is run on Veeam server which has VBR (cloud connect) and VB365 installed, the script ran successfully when it was v11 and v6 but now doesn't produces a document without data after upgrading to v12 and v7. Is it possible this is because it is trying to use basic authentication for a few of the organizations?

**To Reproduce**
Run the script on the server.

**Expected behavior**
A report with data.

**Comment by drtcode** [comment]
Hi @HangTen416, the issue is resolved. It was a regression against a feature that was enhanced after Jun 22. An update will be pushed likely next week sometime. Meanwhile, if you want to run the tool, I'd suggest using [an older version prior to Jun 22](https://github.com/VeeamHub/veeam-healthcheck/releases/tag/1.0.3.520) against your VB365 server(s) -- assuming any [other fixes since](https://github.com/VeeamHub/veeam-healthcheck/releases) (they should only be VBR specific enhancements) don't outweigh doing so.
