### ISSUE TITLE
Malware: Events Summary

### ISSUE THREAD

**Issue by COGRobman** [VeeamHub/veeam-healthcheck#33]
I ran the report and looking at the following part of the report, I'm not sure what to do with the information:

Event/Info | Count
Total Events | 17
Total Objects Flagged | 1
Total Unique Event Types | 2

I have been searching the internet, but not found anything leading me as to what I should be doing next (besides be concerned).

I also turned on "Storage-level corruption guard" on the Maintenance tab in the Advanced Settings window. This window is accessible from the Storage part of the Backup job configuration.

**Comment by adamcongdon** [comment]
Hi,

So that table is just a quick summary from extended malware detection details. Flagged Objects are listed in the following tables "Malware: Infected Objects". Events are not listed here as they made the report look very messy. 

Total Events is the total malware events that you have had flagged. To find more on this, look in your Veeam Backup & Replication Console > History View > Malware Detection > Malware Events. Then review these as needed with your security team. (You can also find this in the CSV files in C:\temp\vHC\Original\VBR\localhostmalware_events.csv)
<img width="300" alt="image" src="https://github.com/user-attachments/assets/ca47eeb1-7a74-4a7c-9fcb-c248da34daef">


Total Unique Event Types is a summary of the events. Basically, you have 17 total events split between 2 unique messages across 1 object (vm/server). Likely you have a single system that is being flagged for a couple of different reasons that you need to check.

Let me know if you need any more help with this!

-AC

**Comment by COGRobman** [comment]
Thank you for that information.

A follow-up question since I'm also part of the security team. It appears the files have been deleted since I can't find the files on the File Server.

The results:
[26.02.2024 21:04:26.164]    <12> Warning (3)    Fileserv01:123ABDC...:d:\...\Canon iR-ADV C2030\UFRII_v20.90_INF:Readme.hta
[26.02.2024 21:04:26.164]    <12> Warning (3)    Fileserv01:123ABDC...:d:\...\Canon iR-ADV C2030\UFRII_v20.85_INF:Readme.hta
[26.02.2024 21:04:26.164]    <12> Warning (3)    Fileserv01:123ABDC...:d:\...\Canon iR-ADV C2030\PCL6_v20.90_INF:Readme.hta
[26.02.2024 21:04:42.961]    <12> Warning (3)    Fileserv01:123ABDC...:d:\Archive\...\Logo:LogoFiles.sonic

Can I "clear" these events? The errors are from prior to my first day on the job.

**Comment by adamcongdon** [comment]
If you've checked and are confident everything is clean, sure you can mark it as clean. If you're looking for some additional help with understanding the scope of the events as far as the Veeam detection is concerned, please open a ticket with support to gain some assistance.

**Comment by COGRobman** [comment]
Sorry. How do I mark it as clean?

**Comment by adamcongdon** [comment]
To be clear, I'm assuming you're asking about clearing the infected machine as being flagged as infected. Here is how to mark the machines as clean: https://helpcenter.veeam.com/docs/backup/vsphere/malware_detection_managing_status.html?zoom_highlight=mark+as+clean&ver=120

If you're asking about clearing the events, the events cannot be cleared until they roll off from the session history.
